# Don't print a new line at the start of the prompt
add_newline = false

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"

[cmd_duration]
format = "[$duration]($style)"
[directory]
format = "[$path]($style)[$read_only]($read_only_style)"
truncate_to_repo = false
truncation_symbol = ".../"
[git_branch]
format = "|[$branch]($style)"
[package]
disabled = true
[ruby]
disabled = true
[rust]
disabled = true

format = "$directory|$git_branch|$git_state"
